### ISSUE TITLE
How to call to perticular user if there are many users connected? 

### ISSUE THREAD

**Issue by iamkhan001** [GetStream/webrtc-in-jetpack-compose#3]
I'm trying to make a video calling app, In my case there are many users if I want to connect to any user using user id or email is there any way to connect a call? 
Please help on this. thanks

**Comment by xuegao-tzx** [comment]
或許你可以嘗試自己寫專用的信令後端實現向對應的用戶發送信息

**Comment by skydoves** [comment]
Hey guys, sorry for the late response. This is an example for 1:1 p2p example. Once I build any great example, I will share it with you. in the meantime, you can check out any ideas from our SDK: https://github.com/getstream/stream-video-android

**Comment by YeonjunNotFR** [comment]
Hello, I don't know if this will help but in my case I solved it by giving the second parameter streamId of the addTrack function

PeerConnection.class
```
public RtpSender addTrack(MediaStreamTrack track, List<String> streamIds)
```

SessionManager.class
```
peerConnection.connection.addTrack(it, listOf(it.id()))
```
Here, "it" is MediaStreamTrack
The "it.id" is the trackId of the track made with makeVideoTrack
```
private val localVideoTrack: VideoTrack by lazy {
        peerConnectionFactory.makeVideoTrack(
            source = videoSource,
            trackId = "${TrackType.VIDEO.type}$ID_SEPARATOR${peerConnectionFactory.sessionId}"
        )
    }
```
Then, you can receive the id from the PeerConnection Observer as follows.
```
 override fun onAddTrack(receiver: RtpReceiver?, mediaStreams: Array<out MediaStream>?) {
        Loggers.Connection.onAddTrack(receiver, mediaStreams)
        val id = mediaStreams?.firstOrNull()?.id ?: return
        val track = receiver?.track() ?: return

        peerConnectionListener.onStreamAdded(id, track)
    }
```

`val (trackType, sessionId) = id.split(ID_SEPARATOR).let { TrackType.typeOf(it.first()) to it.last() }`
